//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLS_Measurement_ToolKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLS_Measurement_ToolKit.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;My first chart using FusionCharts Suite XT&lt;/title&gt;
        ///
        ///&lt;!-- This is from fusioncharts.js --&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///(function(){if(!window.FusionCharts||!window.FusionCharts.version){var d=window,m=d.document,E=d.navigator,v={window:d},k=v.modules={},c=v.interpreters={},P=Object.prototype.toString,b=/msie/i.test(E.userAgent)&amp;&amp;!d.opera,G=/loaded|complete/,a=!1,R=function(){var a=v.ready;v.ready=!0;v.raiseEvent&amp;&amp;(v.readyNotified=!0,v.raiseEvent(&quot;ready&quot;,{version:v.core.version, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AxialTemplate {
            get {
                return ResourceManager.GetString("AxialTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;img src=&quot;{FLSLogo}&quot; height=&quot;42&quot; width=&quot;62&quot;&gt;
        ///&lt;H2 align=&quot;center&quot; &gt;&lt;i&gt;&lt;u&gt;Girth Gear Axial Runout Measurement Report&lt;/u&gt;&lt;/i&gt;&lt;/H2&gt;&lt;br&gt;&lt;br&gt;
        ///&lt;H3&gt;&lt;i&gt;&lt;u&gt;Customer Info/ Label:&lt;/u&gt;&lt;/i&gt;&lt;/H3&gt;&lt;br&gt;&lt;br&gt;
        ///&lt;table style=&quot;border:1px solid black;border-collapse:collapse;&quot;&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;border:1px solid red;&quot;&gt;Customer Name&lt;/td&gt;
        ///&lt;td style=&quot;border:1px solid red;&quot;&gt;{Customer Name}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td style=&quot;border:1px solid red;&quot;&gt;OEM&lt;/td&gt;
        ///&lt;td style=&quot;border:1px solid red;&quot;&gt;{OEM}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td sty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDFTemp {
            get {
                return ResourceManager.GetString("PDFTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;My first chart using FusionCharts Suite XT&lt;/title&gt;
        ///&lt;!-- This is from fusioncharts.js --&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///(function(){if(!window.FusionCharts||!window.FusionCharts.version){var d=window,m=d.document,E=d.navigator,v={window:d},k=v.modules={},c=v.interpreters={},P=Object.prototype.toString,b=/msie/i.test(E.userAgent)&amp;&amp;!d.opera,G=/loaded|complete/,a=!1,R=function(){var a=v.ready;v.ready=!0;v.raiseEvent&amp;&amp;(v.readyNotified=!0,v.raiseEvent(&quot;ready&quot;,{version:v.core.version,no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RadialTemplate {
            get {
                return ResourceManager.GetString("RadialTemplate", resourceCulture);
            }
        }
    }
}
